// eslint-disable-line max-lines
export default {
  locale: 'en',
  messages: {
    'SERVERS.brazil': 'Brazil',
    'SERVERS.europe_nordic_east': 'Europe Nordic and East',
    'SERVERS.europe_west': 'Europe West',
    'SERVERS.republic_of_korea': 'Republic of Korea',
    'SERVERS.latin_america_north': 'Latin America North',
    'SERVERS.latin_america_south': 'Latin America South',
    'SERVERS.north_america': 'North America',
    'SERVERS.oceania': 'Oceania',
    'SERVERS.russia': 'Russia',
    'SERVERS.turkey': 'Turkey',
    'SERVERS.eu_west': 'EU West',
    'SERVERS.eu_east': 'EU East',
    'SERVERS.eu_north': 'EU North',
    'SERVERS.us_northwest': 'US Northwest',
    'SERVERS.us_northeast': 'US Northeast',
    'SERVERS.us_northcentral': 'US Northcentral',
    'SERVERS.us_southwest': 'US Southwest',
    'SERVERS.us_southeast': 'US Southeast',
    'SERVERS.china_shanghai': 'China Shanghai',
    'SERVERS.china_guangzhou': 'China Guangzhou',
    'SERVERS.china_tianjin': 'China Tianjin',
    'SERVERS.australia': 'Australia',
    'SERVERS.chile': 'Chile',
    'SERVERS.emirates': 'Emirates',
    'SERVERS.india': 'India',
    'SERVERS.india_east': 'India East',
    'SERVERS.poland': 'Poland',
    'SERVERS.japan': 'Japan',
    'SERVERS.hong_kong': 'Hong Kong',
    'SERVERS.singapore': 'Singapore',
    'SERVERS.south_africa': 'South Africa',
    'SERVERS.spain': 'Spain',
    'SERVERS.amsterdam': 'Amsterdam',
    'SERVERS.rotterdam': 'Rotterdam',
    'SERVERS.los_angeles': 'Los Angeles',
    'SERVERS.phoenix': 'Phoenix',
    'SERVERS.washington_dc': 'Washington DC',
    'SERVERS.frankfurt': 'Frankfurt',
    'SERVERS.sao_paulo': 'Sao Paulo',
    'GOALS.placeholder_any': 'Any',
    'GOALS.play_for_fun': 'To have fun',
    'GOALS.play_in_amateur_leagues': 'To play competitively',
    'GOALS.become_professional': 'To become a pro team',
    'COUNTRIES.br': 'Brazil',
    'COUNTRIES.de': 'Germany',
    'COUNTRIES.pl': 'Poland',
    'COUNTRIES.ru': 'Russia',
    'COUNTRIES.gb': 'United Kingdom',
    'COUNTRIES.us': 'United States',
    'COUNTRIES.af': 'Afghanistan',
    'COUNTRIES.al': 'Albania',
    'COUNTRIES.dz': 'Algeria',
    'COUNTRIES.as': 'American Samoa',
    'COUNTRIES.ad': 'Andorra',
    'COUNTRIES.ao': 'Angola',
    'COUNTRIES.ai': 'Anguilla',
    'COUNTRIES.aq': 'Antarctica',
    'COUNTRIES.ag': 'Antigua and Barbuda',
    'COUNTRIES.ar': 'Argentina',
    'COUNTRIES.am': 'Armenia',
    'COUNTRIES.aw': 'Aruba',
    'COUNTRIES.au': 'Australia',
    'COUNTRIES.at': 'Austria',
    'COUNTRIES.az': 'Azerbaijan',
    'COUNTRIES.bs': 'Bahamas, The',
    'COUNTRIES.bh': 'Bahrain',
    'COUNTRIES.bd': 'Bangladesh',
    'COUNTRIES.bb': 'Barbados',
    'COUNTRIES.by': 'Belarus',
    'COUNTRIES.be': 'Belgium',
    'COUNTRIES.bz': 'Belize',
    'COUNTRIES.bj': 'Benin',
    'COUNTRIES.bm': 'Bermuda',
    'COUNTRIES.bt': 'Bhutan',
    'COUNTRIES.bo': 'Bolivia',
    'COUNTRIES.ba': 'Bosnia and Herzegovina',
    'COUNTRIES.bw': 'Botswana',
    'COUNTRIES.bv': 'Bouvet Island',
    'COUNTRIES.io': 'British Indian Ocean Territory',
    'COUNTRIES.vg': 'British Virgin Islands',
    'COUNTRIES.bn': 'Brunei',
    'COUNTRIES.bg': 'Bulgaria',
    'COUNTRIES.bf': 'Burkina Faso',
    'COUNTRIES.bi': 'Burundi',
    'COUNTRIES.kh': 'Cambodia',
    'COUNTRIES.cm': 'Cameroon',
    'COUNTRIES.ca': 'Canada',
    'COUNTRIES.cv': 'Cape Verde',
    'COUNTRIES.ky': 'Cayman Islands',
    'COUNTRIES.cf': 'Central African Republic',
    'COUNTRIES.td': 'Chad',
    'COUNTRIES.cl': 'Chile',
    'COUNTRIES.cn': 'China',
    'COUNTRIES.cx': 'Christmas Island',
    'COUNTRIES.cc': 'Cocos (Keeling) Islands',
    'COUNTRIES.co': 'Colombia',
    'COUNTRIES.km': 'Comoros',
    'COUNTRIES.cd': 'Congo, Democratic Republic of the',
    'COUNTRIES.cg': 'Congo, Republic of the',
    'COUNTRIES.ck': 'Cook Islands',
    'COUNTRIES.cr': 'Costa Rica',
    'COUNTRIES.ci': "Cote d'Ivoire",
    'COUNTRIES.hr': 'Croatia',
    'COUNTRIES.cu': 'Cuba',
    'COUNTRIES.cw': 'Curacao',
    'COUNTRIES.cy': 'Cyprus',
    'COUNTRIES.cz': 'Czech Republic',
    'COUNTRIES.dk': 'Denmark',
    'COUNTRIES.dj': 'Djibouti',
    'COUNTRIES.dm': 'Dominica',
    'COUNTRIES.do': 'Dominican Republic',
    'COUNTRIES.tl': 'East Timor',
    'COUNTRIES.ec': 'Ecuador',
    'COUNTRIES.eg': 'Egypt',
    'COUNTRIES.sv': 'El Salvador',
    'COUNTRIES.gq': 'Equatorial Guinea',
    'COUNTRIES.er': 'Eritrea',
    'COUNTRIES.ee': 'Estonia',
    'COUNTRIES.et': 'Ethiopia',
    'COUNTRIES.fk': 'Falkland Islands (Islas Malvinas)',
    'COUNTRIES.fo': 'Faroe Islands',
    'COUNTRIES.fj': 'Fiji',
    'COUNTRIES.fi': 'Finland',
    'COUNTRIES.fr': 'France',
    'COUNTRIES.gf': 'French Guiana',
    'COUNTRIES.pf': 'French Polynesia',
    'COUNTRIES.tf': 'French Southern and Antarctic Lands',
    'COUNTRIES.ga': 'Gabon',
    'COUNTRIES.gm': 'Gambia, The',
    'COUNTRIES.ge': 'Georgia',
    'COUNTRIES.gh': 'Ghana',
    'COUNTRIES.gi': 'Gibraltar',
    'COUNTRIES.gr': 'Greece',
    'COUNTRIES.gl': 'Greenland',
    'COUNTRIES.gd': 'Grenada',
    'COUNTRIES.gp': 'Guadeloupe',
    'COUNTRIES.gu': 'Guam',
    'COUNTRIES.gt': 'Guatemala',
    'COUNTRIES.gg': 'Guernsey',
    'COUNTRIES.gn': 'Guinea',
    'COUNTRIES.gw': 'Guinea-Bissau',
    'COUNTRIES.gy': 'Guyana',
    'COUNTRIES.ht': 'Haiti',
    'COUNTRIES.hm': 'Heard Island and McDonald Islands',
    'COUNTRIES.va': 'Holy See (Vatican City)',
    'COUNTRIES.hn': 'Honduras',
    'COUNTRIES.hk': 'Hong Kong',
    'COUNTRIES.hu': 'Hungary',
    'COUNTRIES.is': 'Iceland',
    'COUNTRIES.in': 'India',
    'COUNTRIES.id': 'Indonesia',
    'COUNTRIES.ir': 'Iran',
    'COUNTRIES.iq': 'Iraq',
    'COUNTRIES.ie': 'Ireland',
    'COUNTRIES.im': 'Isle of Man',
    'COUNTRIES.il': 'Israel',
    'COUNTRIES.it': 'Italy',
    'COUNTRIES.jm': 'Jamaica',
    'COUNTRIES.jp': 'Japan',
    'COUNTRIES.je': 'Jersey',
    'COUNTRIES.jo': 'Jordan',
    'COUNTRIES.kz': 'Kazakhstan',
    'COUNTRIES.ke': 'Kenya',
    'COUNTRIES.ki': 'Kiribati',
    'COUNTRIES.kp': 'Korea, North',
    'COUNTRIES.kr': 'Korea, South',
    'COUNTRIES.xk': 'Kosovo',
    'COUNTRIES.kw': 'Kuwait',
    'COUNTRIES.kg': 'Kyrgyzstan',
    'COUNTRIES.la': 'Laos',
    'COUNTRIES.lv': 'Latvia',
    'COUNTRIES.lb': 'Lebanon',
    'COUNTRIES.ls': 'Lesotho',
    'COUNTRIES.lr': 'Liberia',
    'COUNTRIES.ly': 'Libyan Arab',
    'COUNTRIES.li': 'Liechtenstein',
    'COUNTRIES.lt': 'Lithuania',
    'COUNTRIES.lu': 'Luxembourg',
    'COUNTRIES.mo': 'Macau',
    'COUNTRIES.mg': 'Madagascar',
    'COUNTRIES.mw': 'Malawi',
    'COUNTRIES.my': 'Malaysia',
    'COUNTRIES.mv': 'Maldives',
    'COUNTRIES.ml': 'Mali',
    'COUNTRIES.mt': 'Malta',
    'COUNTRIES.mh': 'Marshall Islands',
    'COUNTRIES.mq': 'Martinique',
    'COUNTRIES.mr': 'Mauritania',
    'COUNTRIES.mu': 'Mauritius',
    'COUNTRIES.yt': 'Mayotte',
    'COUNTRIES.mx': 'Mexico',
    'COUNTRIES.fm': 'Micronesia, Federated States of',
    'COUNTRIES.md': 'Moldova, Republic of',
    'COUNTRIES.mc': 'Monaco',
    'COUNTRIES.mn': 'Mongolia',
    'COUNTRIES.me': 'Montenegro',
    'COUNTRIES.ms': 'Montserrat',
    'COUNTRIES.ma': 'Morocco',
    'COUNTRIES.mz': 'Mozambique',
    'COUNTRIES.mm': 'Myanmar',
    'COUNTRIES.na': 'Namibia',
    'COUNTRIES.nr': 'Nauru',
    'COUNTRIES.np': 'Nepal',
    'COUNTRIES.nl': 'Netherlands',
    'COUNTRIES.nc': 'New Caledonia',
    'COUNTRIES.nz': 'New Zealand',
    'COUNTRIES.ni': 'Nicaragua',
    'COUNTRIES.ne': 'Niger',
    'COUNTRIES.ng': 'Nigeria',
    'COUNTRIES.nu': 'Niue',
    'COUNTRIES.nf': 'Norfolk Island',
    'COUNTRIES.mp': 'Northern Mariana Islands',
    'COUNTRIES.no': 'Norway',
    'COUNTRIES.om': 'Oman',
    'COUNTRIES.pk': 'Pakistan',
    'COUNTRIES.pw': 'Palau',
    'COUNTRIES.ps': 'Palestine, State of',
    'COUNTRIES.pa': 'Panama',
    'COUNTRIES.pg': 'Papua New Guinea',
    'COUNTRIES.py': 'Paraguay',
    'COUNTRIES.pe': 'Peru',
    'COUNTRIES.ph': 'Philippines',
    'COUNTRIES.pn': 'Pitcairn Islands',
    'COUNTRIES.pt': 'Portugal',
    'COUNTRIES.pr': 'Puerto Rico',
    'COUNTRIES.qa': 'Qatar',
    'COUNTRIES.re': 'Reunion',
    'COUNTRIES.ro': 'Romania',
    'COUNTRIES.rw': 'Rwanda',
    'COUNTRIES.bl': 'Saint Barthelemy',
    'COUNTRIES.sh': 'Saint Helena',
    'COUNTRIES.kn': 'Saint Kitts and Nevis',
    'COUNTRIES.lc': 'Saint Lucia',
    'COUNTRIES.mf': 'Saint Martin',
    'COUNTRIES.pm': 'Saint Pierre and Miquelon',
    'COUNTRIES.vc': 'Saint Vincent and the Grenadines',
    'COUNTRIES.ws': 'Samoa',
    'COUNTRIES.sm': 'San Marino',
    'COUNTRIES.st': 'Sao Tome and Principe',
    'COUNTRIES.sa': 'Saudi Arabia',
    'COUNTRIES.sn': 'Senegal',
    'COUNTRIES.rs': 'Serbia',
    'COUNTRIES.sc': 'Seychelles',
    'COUNTRIES.sl': 'Sierra Leone',
    'COUNTRIES.sg': 'Singapore',
    'COUNTRIES.sx': 'Sint Maarten',
    'COUNTRIES.sk': 'Slovakia',
    'COUNTRIES.si': 'Slovenia',
    'COUNTRIES.sb': 'Solomon Islands',
    'COUNTRIES.so': 'Somalia',
    'COUNTRIES.za': 'South Africa',
    'COUNTRIES.gs': 'South Georgia and the Islands',
    'COUNTRIES.es': 'Spain',
    'COUNTRIES.lk': 'Sri Lanka',
    'COUNTRIES.sd': 'Sudan',
    'COUNTRIES.sr': 'Suriname',
    'COUNTRIES.sj': 'Svalbard',
    'COUNTRIES.sz': 'Swaziland',
    'COUNTRIES.se': 'Sweden',
    'COUNTRIES.ch': 'Switzerland',
    'COUNTRIES.sy': 'Syrian Arab Republic',
    'COUNTRIES.tw': 'Taiwan',
    'COUNTRIES.tj': 'Tajikistan',
    'COUNTRIES.tz': 'Tanzania, United Republic of',
    'COUNTRIES.th': 'Thailand',
    'COUNTRIES.mk': 'The Former Yugoslav Republic of Macedonia',
    'COUNTRIES.tg': 'Togo',
    'COUNTRIES.tk': 'Tokelau',
    'COUNTRIES.to': 'Tonga',
    'COUNTRIES.tt': 'Trinidad and Tobago',
    'COUNTRIES.tn': 'Tunisia',
    'COUNTRIES.tr': 'Turkey',
    'COUNTRIES.tm': 'Turkmenistan',
    'COUNTRIES.tc': 'Turks and Caicos Islands',
    'COUNTRIES.tv': 'Tuvalu',
    'COUNTRIES.ug': 'Uganda',
    'COUNTRIES.ua': 'Ukraine',
    'COUNTRIES.ae': 'United Arab Emirates',
    'COUNTRIES.uy': 'Uruguay',
    'COUNTRIES.uz': 'Uzbekistan',
    'COUNTRIES.vu': 'Vanuatu',
    'COUNTRIES.ve': 'Venezuela',
    'COUNTRIES.vn': 'Vietnam',
    'COUNTRIES.vi': 'Virgin Islands (US)',
    'COUNTRIES.wf': 'Wallis and Futuna',
    'COUNTRIES.eh': 'Western Sahara',
    'COUNTRIES.ye': 'Yemen',
    'COUNTRIES.zm': 'Zambia',
    'COUNTRIES.zw': 'Zimbabwe',
    'LANGUAGES.en': 'English',
    'LANGUAGES.es': 'Spanish',
    'LANGUAGES.de': 'German',
    'LANGUAGES.ru': 'Russian',
    'LANGUAGES.it': 'Italian',
    'LANGUAGES.zh': 'Chinese',
    'LANGUAGES.ab': 'Abkhazian',
    'LANGUAGES.aa': 'Afar',
    'LANGUAGES.af': 'Afrikaans',
    'LANGUAGES.ak': 'Akan',
    'LANGUAGES.sq': 'Albanian',
    'LANGUAGES.am': 'Amharic',
    'LANGUAGES.ar': 'Arabic',
    'LANGUAGES.an': 'Aragonese',
    'LANGUAGES.hy': 'Armenian',
    'LANGUAGES.as': 'Assamese',
    'LANGUAGES.av': 'Avaric',
    'LANGUAGES.ae': 'Avestan',
    'LANGUAGES.ay': 'Aymara',
    'LANGUAGES.az': 'Azerbaijani',
    'LANGUAGES.bm': 'Bambara',
    'LANGUAGES.ba': 'Bashkir',
    'LANGUAGES.eu': 'Basque',
    'LANGUAGES.be': 'Belarusian',
    'LANGUAGES.bn': 'Bengali',
    'LANGUAGES.bh': 'Bihari languages',
    'LANGUAGES.bi': 'Bislama',
    'LANGUAGES.nb': 'Bokmål',
    'LANGUAGES.bs': 'Bosnian',
    'LANGUAGES.br': 'Breton',
    'LANGUAGES.bg': 'Bulgarian',
    'LANGUAGES.my': 'Burmese',
    'LANGUAGES.ca': 'Catalan; Valencian',
    'LANGUAGES.km': 'Central Khmer',
    'LANGUAGES.ch': 'Chamorro',
    'LANGUAGES.ce': 'Chechen',
    'LANGUAGES.cv': 'Chuvash',
    'LANGUAGES.kw': 'Cornish',
    'LANGUAGES.co': 'Corsican',
    'LANGUAGES.cr': 'Cree',
    'LANGUAGES.hr': 'Croatian',
    'LANGUAGES.cs': 'Czech',
    'LANGUAGES.da': 'Danish',
    'LANGUAGES.nl': 'Dutch; Flemish',
    'LANGUAGES.dz': 'Dzongkha',
    'LANGUAGES.eo': 'Esperanto',
    'LANGUAGES.et': 'Estonian',
    'LANGUAGES.ee': 'Ewe',
    'LANGUAGES.fo': 'Faroese',
    'LANGUAGES.fj': 'Fijian',
    'LANGUAGES.fi': 'Finnish',
    'LANGUAGES.fr': 'French',
    'LANGUAGES.ff': 'Fulah',
    'LANGUAGES.gd': 'Gaelic',
    'LANGUAGES.gl': 'Galician',
    'LANGUAGES.lg': 'Ganda',
    'LANGUAGES.ka': 'Georgian',
    'LANGUAGES.el': 'Greek',
    'LANGUAGES.gn': 'Guarani',
    'LANGUAGES.gu': 'Gujarati',
    'LANGUAGES.ht': 'Haitian Creole',
    'LANGUAGES.ha': 'Hausa',
    'LANGUAGES.he': 'Hebrew',
    'LANGUAGES.hz': 'Herero',
    'LANGUAGES.hi': 'Hindi',
    'LANGUAGES.ho': 'Hiri Motu',
    'LANGUAGES.hu': 'Hungarian',
    'LANGUAGES.is': 'Icelandic',
    'LANGUAGES.io': 'Ido',
    'LANGUAGES.ig': 'Igbo',
    'LANGUAGES.id': 'Indonesian',
    'LANGUAGES.ia': 'Interlingua',
    'LANGUAGES.iu': 'Inuktitut',
    'LANGUAGES.ik': 'Inupiaq',
    'LANGUAGES.ga': 'Irish',
    'LANGUAGES.ja': 'Japanese',
    'LANGUAGES.jv': 'Javanese',
    'LANGUAGES.kl': 'Kalaallisut',
    'LANGUAGES.kn': 'Kannada',
    'LANGUAGES.kr': 'Kanuri',
    'LANGUAGES.ks': 'Kashmiri',
    'LANGUAGES.kk': 'Kazakh',
    'LANGUAGES.ki': 'Kikuyu',
    'LANGUAGES.rw': 'Kinyarwanda',
    'LANGUAGES.kv': 'Komi',
    'LANGUAGES.kg': 'Kongo',
    'LANGUAGES.ko': 'Korean',
    'LANGUAGES.ku': 'Kurdish',
    'LANGUAGES.kj': 'Kwanyama',
    'LANGUAGES.ky': 'Kyrgyz',
    'LANGUAGES.lo': 'Lao',
    'LANGUAGES.la': 'Latin',
    'LANGUAGES.lv': 'Latvian',
    'LANGUAGES.li': 'Limburgish',
    'LANGUAGES.ln': 'Lingala',
    'LANGUAGES.lt': 'Lithuanian',
    'LANGUAGES.lu': 'Luba-Katanga',
    'LANGUAGES.lb': 'Luxembourgish',
    'LANGUAGES.mk': 'Macedonian',
    'LANGUAGES.mg': 'Malagasy',
    'LANGUAGES.ms': 'Malay',
    'LANGUAGES.ml': 'Malayalam',
    'LANGUAGES.dv': 'Maldivian',
    'LANGUAGES.mt': 'Maltese',
    'LANGUAGES.gv': 'Manx',
    'LANGUAGES.mi': 'Maori',
    'LANGUAGES.mr': 'Marathi',
    'LANGUAGES.mh': 'Marshallese',
    'LANGUAGES.mn': 'Mongolian',
    'LANGUAGES.na': 'Nauru',
    'LANGUAGES.nv': 'Navajo; Navaho',
    'LANGUAGES.nd': 'Ndebele, North',
    'LANGUAGES.nr': 'Ndebele, South',
    'LANGUAGES.ng': 'Ndonga',
    'LANGUAGES.ne': 'Nepali',
    'LANGUAGES.se': 'Northern Sami',
    'LANGUAGES.no': 'Norwegian',
    'LANGUAGES.ny': 'Nyanja',
    'LANGUAGES.nn': 'Nynorsk',
    'LANGUAGES.oc': 'Occitan',
    'LANGUAGES.oj': 'Ojibwa',
    'LANGUAGES.or': 'Oriya',
    'LANGUAGES.om': 'Oromo',
    'LANGUAGES.os': 'Ossetian',
    'LANGUAGES.pi': 'Pali',
    'LANGUAGES.ps': 'Pashto',
    'LANGUAGES.fa': 'Persian',
    'LANGUAGES.pl': 'Polish',
    'LANGUAGES.pt': 'Portuguese',
    'LANGUAGES.pa': 'Punjabi',
    'LANGUAGES.qu': 'Quechua',
    'LANGUAGES.ro': 'Romanian; Moldovan',
    'LANGUAGES.rm': 'Romansh',
    'LANGUAGES.rn': 'Rundi',
    'LANGUAGES.sm': 'Samoan',
    'LANGUAGES.sg': 'Sango',
    'LANGUAGES.sa': 'Sanskrit',
    'LANGUAGES.sc': 'Sardinian',
    'LANGUAGES.sr': 'Serbian',
    'LANGUAGES.sn': 'Shona',
    'LANGUAGES.ii': 'Sichuan Yi; Nuosu',
    'LANGUAGES.sd': 'Sindhi',
    'LANGUAGES.si': 'Sinhala; Sinhalese',
    'LANGUAGES.sk': 'Slovak',
    'LANGUAGES.sl': 'Slovenian',
    'LANGUAGES.so': 'Somali',
    'LANGUAGES.st': 'Sotho, Southern',
    'LANGUAGES.su': 'Sundanese',
    'LANGUAGES.sw': 'Swahili',
    'LANGUAGES.ss': 'Swati',
    'LANGUAGES.sv': 'Swedish',
    'LANGUAGES.tl': 'Tagalog',
    'LANGUAGES.ty': 'Tahitian',
    'LANGUAGES.tg': 'Tajik',
    'LANGUAGES.ta': 'Tamil',
    'LANGUAGES.tt': 'Tatar',
    'LANGUAGES.te': 'Telugu',
    'LANGUAGES.th': 'Thai',
    'LANGUAGES.bo': 'Tibetan',
    'LANGUAGES.ti': 'Tigrinya',
    'LANGUAGES.to': 'Tonga (Tonga Islands)',
    'LANGUAGES.ts': 'Tsonga',
    'LANGUAGES.tn': 'Tswana',
    'LANGUAGES.tr': 'Turkish',
    'LANGUAGES.tk': 'Turkmen',
    'LANGUAGES.tw': 'Twi',
    'LANGUAGES.ug': 'Uighur; Uyghur',
    'LANGUAGES.uk': 'Ukrainian',
    'LANGUAGES.ur': 'Urdu',
    'LANGUAGES.uz': 'Uzbek',
    'LANGUAGES.ve': 'Venda',
    'LANGUAGES.vi': 'Vietnamese',
    'LANGUAGES.vo': 'Volapük',
    'LANGUAGES.wa': 'Walloon',
    'LANGUAGES.cy': 'Welsh',
    'LANGUAGES.fy': 'Western Frisian',
    'LANGUAGES.wo': 'Wolof',
    'LANGUAGES.xh': 'Xhosa',
    'LANGUAGES.yi': 'Yiddish',
    'LANGUAGES.yo': 'Yoruba',
    'LANGUAGES.za': 'Zhuang; Chuang',
    'LANGUAGES.zu': 'Zulu',
    'MAPS.ar_baggage': 'Baggage',
    'MAPS.ar_monastery': 'Monastery',
    'MAPS.ar_shoots': 'Shoots',
    'MAPS.cs_assault': 'Assault',
    'MAPS.cs_italy': 'Italy',
    'MAPS.cs_militia': 'Militia',
    'MAPS.cs_office': 'Office',
    'MAPS.de_aztec': 'Aztec',
    'MAPS.de_bank': 'Bank',
    'MAPS.de_cache': 'Cache',
    'MAPS.de_canals': 'Canals',
    'MAPS.de_cbble': 'Cobblestone',
    'MAPS.de_cobblestone': 'Cobblestone',
    'MAPS.de_dust': 'Dust',
    'MAPS.de_dust2': 'Dust II',
    'MAPS.de_inferno': 'Inferno',
    'MAPS.de_inferno_a': 'Inferno (Bombsite A)',
    'MAPS.de_lake': 'Lake',
    'MAPS.de_mirage': 'Mirage',
    'MAPS.de_mirage_wingman_b': 'Mirage Wingman (Bombsite B)',
    'MAPS.de_nuke': 'Nuke',
    'MAPS.de_overpass': 'Overpass',
    'MAPS.de_overpass_b': 'Overpass (Bombsite B)',
    'MAPS.de_safehouse': 'Safehouse',
    'MAPS.de_shortcbble': 'Cobblestone (Bombsite B)',
    'MAPS.de_shortdust': 'Shortdust',
    'MAPS.de_shortdust2': 'Shortdust II',
    'MAPS.de_shortnuke': 'Shortnuke',
    'MAPS.de_shorttrain': 'Short Train',
    'MAPS.de_stmarc': 'St. Marc',
    'MAPS.de_sugarcane': 'Sugarcane',
    'MAPS.de_train': 'Train',
    'MAPS.de_vertigo': 'Vertigo',
    'MAPS.de_vertigo_b': 'Vertigo (Bombsite B)',
    'MAPS.gd_rialto': 'Rialto',
    'MAPS.gd_train': 'Train (Bombsite A)',
    'ROLES.CSGO.sniper': 'Sniper',
    'ROLES.CSGO.assault': 'Assault',
    'ROLES.CSGO.support': 'Support',
    'ROLES.CSGO.captain': 'Captain',
    'ROLES.CSGO.strategist': 'Strategist',
    'ROLES.CSGO.coach': 'Coach',
    'ROLES.LOL.ad_carry': 'ADC',
    'ROLES.LOL.support': 'Support',
    'ROLES.LOL.jungler': 'Jungler',
    'ROLES.LOL.top_lane': 'Top Lane',
    'ROLES.LOL.mid_lane': 'Mid Lane',
    'ROLES.LOL.drafter': 'Drafter',
    'ROLES.LOL.shot_caller': 'Shot Caller',
    'ROLES.LOL.in_game_leader_coordinator': 'Captain / IGL',
    'RANKS.CSGO.silver_i': 'Silver I',
    'RANKS.CSGO.silver_ii': 'Silver II',
    'RANKS.CSGO.silver_iii': 'Silver III',
    'RANKS.CSGO.silver_iv': 'Silver IV',
    'RANKS.CSGO.silver_elite': 'Silver Elite',
    'RANKS.CSGO.silver_elite_master': 'Silver Elite Master',
    'RANKS.CSGO.goals_nova_i': 'Gold Nova I',
    'RANKS.CSGO.goals_nova_ii': 'Gold Nova II',
    'RANKS.CSGO.goals_nova_iii': 'Gold Nova III',
    'RANKS.CSGO.goals_nova_master': 'Gold Nova Master',
    'RANKS.CSGO.master_guardian_i': 'Master Guardian I',
    'RANKS.CSGO.master_guardian_ii': 'Master Guardian II',
    'RANKS.CSGO.master_guardian_elite': 'Master Guardian Elite',
    'RANKS.CSGO.distinguished_master_guardian': 'Distinguished Master Guardian',
    'RANKS.CSGO.legendary_eagle': 'Legendary Eagle',
    'RANKS.CSGO.legendary_eagle_master': 'Legendary Eagle Master',
    'RANKS.CSGO.supreme_master_first_class': 'Supreme Master First Class',
    'RANKS.CSGO.global_elite': 'The Global Elite',
    'RANKS.LOL.unranked': 'Unranked',
    'RANKS.LOL.placeholder_from': 'From',
    'RANKS.LOL.placeholder_to': 'To',
    'RANKS.LOL.iron_i': 'Iron I',
    'RANKS.LOL.iron_ii': 'Iron II',
    'RANKS.LOL.iron_iii': 'Iron III',
    'RANKS.LOL.iron_iv': 'Iron IV',
    'RANKS.LOL.bronze_i': 'Bronze I',
    'RANKS.LOL.bronze_ii': 'Bronze II',
    'RANKS.LOL.bronze_iii': 'Bronze III',
    'RANKS.LOL.bronze_iv': 'Bronze IV',
    'RANKS.LOL.silver_i': 'Silver I',
    'RANKS.LOL.silver_ii': 'Silver II',
    'RANKS.LOL.silver_iii': 'Silver III',
    'RANKS.LOL.silver_iv': 'Silver IV',
    'RANKS.LOL.gold_i': 'Gold I',
    'RANKS.LOL.gold_ii': 'Gold II',
    'RANKS.LOL.gold_iii': 'Gold III',
    'RANKS.LOL.gold_iv': 'Gold IV',
    'RANKS.LOL.platinum_i': 'Platinum I',
    'RANKS.LOL.platinum_ii': 'Platinum II',
    'RANKS.LOL.platinum_iii': 'Platinum III',
    'RANKS.LOL.platinum_iv': 'Platinum IV',
    'RANKS.LOL.diamond_i': 'Diamond I',
    'RANKS.LOL.diamond_ii': 'Diamond II',
    'RANKS.LOL.diamond_iii': 'Diamond III',
    'RANKS.LOL.diamond_iv': 'Diamond IV',
    'RANKS.LOL.master_i': 'Master',
    'RANKS.LOL.challenger_i': 'Challenger',
    'RANKS.LOL.grandmaster_i': 'GrandMaster'
  },
  localeData: [
    {
      locale: 'en',
      fields: {
        year: {
          displayName: 'year',
          relative: { '0': 'this year', '1': 'next year', '-1': 'last year' },
          relativeTime: {
            future: { one: 'in {0} year', other: 'in {0} years' },
            past: { one: '{0} year ago', other: '{0} years ago' }
          }
        },
        month: {
          displayName: 'month',
          relative: {
            '0': 'this month',
            '1': 'next month',
            '-1': 'last month'
          },
          relativeTime: {
            future: { one: 'in {0} month', other: 'in {0} months' },
            past: { one: '{0} month ago', other: '{0} months ago' }
          }
        },
        day: {
          displayName: 'day',
          relative: { '0': 'today', '1': 'tomorrow', '-1': 'yesterday' },
          relativeTime: {
            future: { one: 'in {0} day', other: 'in {0} days' },
            past: { one: '{0} day ago', other: '{0} days ago' }
          }
        },
        hour: {
          displayName: 'hour',
          relative: { '0': 'this hour' },
          relativeTime: {
            future: { one: 'in {0} hour', other: 'in {0} hours' },
            past: { one: '{0} hour ago', other: '{0} hours ago' }
          }
        },
        minute: {
          displayName: 'minute',
          relative: { '0': 'this minute' },
          relativeTime: {
            future: { one: 'in {0} minute', other: 'in {0} minutes' },
            past: { one: '{0} minute ago', other: '{0} minutes ago' }
          }
        },
        second: {
          displayName: 'second',
          relative: { '0': 'now' },
          relativeTime: {
            future: { one: 'in {0} second', other: 'in {0} seconds' },
            past: { one: '{0} second ago', other: '{0} seconds ago' }
          }
        }
      }
    },
    { locale: 'en-001', parentLocale: 'en' },
    { locale: 'en-150', parentLocale: 'en-001' },
    { locale: 'en-AG', parentLocale: 'en-001' },
    { locale: 'en-AI', parentLocale: 'en-001' },
    { locale: 'en-AS', parentLocale: 'en' },
    { locale: 'en-AT', parentLocale: 'en-150' },
    { locale: 'en-AU', parentLocale: 'en-001' },
    { locale: 'en-BB', parentLocale: 'en-001' },
    { locale: 'en-BE', parentLocale: 'en-001' },
    { locale: 'en-BI', parentLocale: 'en' },
    { locale: 'en-BM', parentLocale: 'en-001' },
    { locale: 'en-BS', parentLocale: 'en-001' },
    { locale: 'en-BW', parentLocale: 'en-001' },
    { locale: 'en-BZ', parentLocale: 'en-001' },
    { locale: 'en-CA', parentLocale: 'en-001' },
    { locale: 'en-CC', parentLocale: 'en-001' },
    { locale: 'en-CH', parentLocale: 'en-150' },
    { locale: 'en-CK', parentLocale: 'en-001' },
    { locale: 'en-CM', parentLocale: 'en-001' },
    { locale: 'en-CX', parentLocale: 'en-001' },
    { locale: 'en-CY', parentLocale: 'en-001' },
    { locale: 'en-DE', parentLocale: 'en-150' },
    { locale: 'en-DG', parentLocale: 'en-001' },
    { locale: 'en-DK', parentLocale: 'en-150' },
    { locale: 'en-DM', parentLocale: 'en-001' },
    {
      locale: 'en-Dsrt',
      fields: {
        year: {
          displayName: 'Year',
          relative: { '0': 'this year', '1': 'next year', '-1': 'last year' },
          relativeTime: {
            future: { other: '+{0} y' },
            past: { other: '-{0} y' }
          }
        },
        month: {
          displayName: 'Month',
          relative: {
            '0': 'this month',
            '1': 'next month',
            '-1': 'last month'
          },
          relativeTime: {
            future: { other: '+{0} m' },
            past: { other: '-{0} m' }
          }
        },
        day: {
          displayName: 'Day',
          relative: { '0': 'today', '1': 'tomorrow', '-1': 'yesterday' },
          relativeTime: {
            future: { other: '+{0} d' },
            past: { other: '-{0} d' }
          }
        },
        hour: {
          displayName: 'Hour',
          relative: { '0': 'this hour' },
          relativeTime: {
            future: { other: '+{0} h' },
            past: { other: '-{0} h' }
          }
        },
        minute: {
          displayName: 'Minute',
          relative: { '0': 'this minute' },
          relativeTime: {
            future: { other: '+{0} min' },
            past: { other: '-{0} min' }
          }
        },
        second: {
          displayName: 'Second',
          relative: { '0': 'now' },
          relativeTime: {
            future: { other: '+{0} s' },
            past: { other: '-{0} s' }
          }
        }
      }
    },
    { locale: 'en-ER', parentLocale: 'en-001' },
    { locale: 'en-FI', parentLocale: 'en-150' },
    { locale: 'en-FJ', parentLocale: 'en-001' },
    { locale: 'en-FK', parentLocale: 'en-001' },
    { locale: 'en-FM', parentLocale: 'en-001' },
    { locale: 'en-GB', parentLocale: 'en-001' },
    { locale: 'en-GD', parentLocale: 'en-001' },
    { locale: 'en-GG', parentLocale: 'en-001' },
    { locale: 'en-GH', parentLocale: 'en-001' },
    { locale: 'en-GI', parentLocale: 'en-001' },
    { locale: 'en-GM', parentLocale: 'en-001' },
    { locale: 'en-GU', parentLocale: 'en' },
    { locale: 'en-GY', parentLocale: 'en-001' },
    { locale: 'en-HK', parentLocale: 'en-001' },
    { locale: 'en-IE', parentLocale: 'en-001' },
    { locale: 'en-IL', parentLocale: 'en-001' },
    { locale: 'en-IM', parentLocale: 'en-001' },
    { locale: 'en-IN', parentLocale: 'en-001' },
    { locale: 'en-IO', parentLocale: 'en-001' },
    { locale: 'en-JE', parentLocale: 'en-001' },
    { locale: 'en-JM', parentLocale: 'en-001' },
    { locale: 'en-KE', parentLocale: 'en-001' },
    { locale: 'en-KI', parentLocale: 'en-001' },
    { locale: 'en-KN', parentLocale: 'en-001' },
    { locale: 'en-KY', parentLocale: 'en-001' },
    { locale: 'en-LC', parentLocale: 'en-001' },
    { locale: 'en-LR', parentLocale: 'en-001' },
    { locale: 'en-LS', parentLocale: 'en-001' },
    { locale: 'en-MG', parentLocale: 'en-001' },
    { locale: 'en-MH', parentLocale: 'en' },
    { locale: 'en-MO', parentLocale: 'en-001' },
    { locale: 'en-MP', parentLocale: 'en' },
    { locale: 'en-MS', parentLocale: 'en-001' },
    { locale: 'en-MT', parentLocale: 'en-001' },
    { locale: 'en-MU', parentLocale: 'en-001' },
    { locale: 'en-MW', parentLocale: 'en-001' },
    { locale: 'en-MY', parentLocale: 'en-001' },
    { locale: 'en-NA', parentLocale: 'en-001' },
    { locale: 'en-NF', parentLocale: 'en-001' },
    { locale: 'en-NG', parentLocale: 'en-001' },
    { locale: 'en-NL', parentLocale: 'en-150' },
    { locale: 'en-NR', parentLocale: 'en-001' },
    { locale: 'en-NU', parentLocale: 'en-001' },
    { locale: 'en-NZ', parentLocale: 'en-001' },
    { locale: 'en-PG', parentLocale: 'en-001' },
    { locale: 'en-PH', parentLocale: 'en-001' },
    { locale: 'en-PK', parentLocale: 'en-001' },
    { locale: 'en-PN', parentLocale: 'en-001' },
    { locale: 'en-PR', parentLocale: 'en' },
    { locale: 'en-PW', parentLocale: 'en-001' },
    { locale: 'en-RW', parentLocale: 'en-001' },
    { locale: 'en-SB', parentLocale: 'en-001' },
    { locale: 'en-SC', parentLocale: 'en-001' },
    { locale: 'en-SD', parentLocale: 'en-001' },
    { locale: 'en-SE', parentLocale: 'en-150' },
    { locale: 'en-SG', parentLocale: 'en-001' },
    { locale: 'en-SH', parentLocale: 'en-001' },
    { locale: 'en-SI', parentLocale: 'en-150' },
    { locale: 'en-SL', parentLocale: 'en-001' },
    { locale: 'en-SS', parentLocale: 'en-001' },
    { locale: 'en-SX', parentLocale: 'en-001' },
    { locale: 'en-SZ', parentLocale: 'en-001' },
    {
      locale: 'en-Shaw',
      fields: {
        year: {
          displayName: 'Year',
          relative: { '0': 'this year', '1': 'next year', '-1': 'last year' },
          relativeTime: {
            future: { other: '+{0} y' },
            past: { other: '-{0} y' }
          }
        },
        month: {
          displayName: 'Month',
          relative: {
            '0': 'this month',
            '1': 'next month',
            '-1': 'last month'
          },
          relativeTime: {
            future: { other: '+{0} m' },
            past: { other: '-{0} m' }
          }
        },
        day: {
          displayName: 'Day',
          relative: { '0': 'today', '1': 'tomorrow', '-1': 'yesterday' },
          relativeTime: {
            future: { other: '+{0} d' },
            past: { other: '-{0} d' }
          }
        },
        hour: {
          displayName: 'Hour',
          relative: { '0': 'this hour' },
          relativeTime: {
            future: { other: '+{0} h' },
            past: { other: '-{0} h' }
          }
        },
        minute: {
          displayName: 'Minute',
          relative: { '0': 'this minute' },
          relativeTime: {
            future: { other: '+{0} min' },
            past: { other: '-{0} min' }
          }
        },
        second: {
          displayName: 'Second',
          relative: { '0': 'now' },
          relativeTime: {
            future: { other: '+{0} s' },
            past: { other: '-{0} s' }
          }
        }
      }
    },
    { locale: 'en-TC', parentLocale: 'en-001' },
    { locale: 'en-TK', parentLocale: 'en-001' },
    { locale: 'en-TO', parentLocale: 'en-001' },
    { locale: 'en-TT', parentLocale: 'en-001' },
    { locale: 'en-TV', parentLocale: 'en-001' },
    { locale: 'en-TZ', parentLocale: 'en-001' },
    { locale: 'en-UG', parentLocale: 'en-001' },
    { locale: 'en-UM', parentLocale: 'en' },
    { locale: 'en-US', parentLocale: 'en' },
    { locale: 'en-VC', parentLocale: 'en-001' },
    { locale: 'en-VG', parentLocale: 'en-001' },
    { locale: 'en-VI', parentLocale: 'en' },
    { locale: 'en-VU', parentLocale: 'en-001' },
    { locale: 'en-WS', parentLocale: 'en-001' },
    { locale: 'en-ZA', parentLocale: 'en-001' },
    { locale: 'en-ZM', parentLocale: 'en-001' },
    { locale: 'en-ZW', parentLocale: 'en-001' }
  ]
}
